name: Deploy iOS App

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify Environment
        run: |
          echo "Current User:"
          whoami

          echo "Ruby Version:"
          ruby -v

          echo "Xcode Version:"
          xcodebuild -version

          echo "Fastlane Location:"
          which fastlane

          echo "Fastlane Version:"
          fastlane --version

      - name: Create App Store Connect API Key
        env:
          APP_STORE_CONNECT_API_KEY_B64: ${{ secrets.APP_STORE_CONNECT_API_KEY_B64 }}
        run: |
          echo "$APP_STORE_CONNECT_API_KEY_B64" | base64 --decode > AuthKey.p8

      - name: Deploy to TestFlight
        env:
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_B64: ${{ secrets.APP_STORE_CONNECT_API_KEY_B64 }}

          APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
          ITC_TEAM_ID: ${{ secrets.ITC_TEAM_ID }}

          XCODE_PROJECT: ${{ secrets.XCODE_PROJECT }}
          XCODE_SCHEME: ${{ secrets.XCODE_SCHEME }}
        run: |
          fastlane beta --verbose

      - name: Cleanup
        if: always()
        run: |
          rm -f AuthKey.p8